<?php

/**
 * @file
 * Contains dom_notifications.module.
 */

/**
 * Implements hook_cron().
 */
function dom_notifications_cron() {
  $last_check = \Drupal::state()->get('dom_notifications.delete_check', 0);
  $request_time = \Drupal::time()->getRequestTime();

  // Execute only once every day, so it won't be cleaning up too often.
  if ($request_time > $last_check + 24 * 60 * 60) {
    /** @var \Drupal\dom_notifications\DomNotificationsServiceInterface $notifications_service */
    $notifications_service = \Drupal::service('dom_notifications.service');
    $notifications_service->executeCleaningUp();

    \Drupal::state()->set('dom_notifications.delete_check', $request_time);
  }
}

/**
 * Implements hook_entity_update().
 */
function dom_notifications_entity_update(Drupal\Core\Entity\EntityInterface $entity) {
  $related_notifications = \Drupal::entityTypeManager()
    ->getStorage('dom_notification')
    ->loadByProperties([
      'related_entity_type' => $entity->getEntityTypeId(),
      'related_entity_id' => $entity->id(),
    ]);

  if (empty($related_notifications)) {
    return;
  }

  $tags = [];
  foreach ($related_notifications as $notification) {
    $tags = array_merge($tags, $notification->getCacheTags());
  }
  \Drupal\Core\Cache\Cache::invalidateTags($tags);
}
