dom_notifications_stacking.settings:
  type: config_object
  mapping:
    channels:
      type: mapping
      label: 'Configs for stacking per channel'
      mapping:
        channel_plugin:
          type: string
          label: 'Plugin ID of a notification channel'
        stack:
          type: number
          label: 'Number of notifications per stack, 1 to disable stacking'
        message:
          type: string
          label: 'Message to use for stacked notification'
        uri:
          type: uri
          label: 'Uri to lead user to after clicking on stacked notification'
        flag:
          type: boolean
          label: 'Indicates if the notification is a global or local'
