<?php

/**
 * @file
 * Contains dom_notifications_firebase.module.
 */

use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_ENTITY_TYPE_presave().
 */
function dom_notifications_firebase_dom_notification_presave(EntityInterface $entity) {
  /** @var \Drupal\dom_notifications\Entity\DomNotificationInterface $entity */
  $just_published = !empty($entity->original)
    ? !$entity->original->isPublished() && $entity->isPublished()
    : $entity->isPublished();

  if (!$just_published) {
    return;
  }

  $queue = \Drupal::queue('dom_notifications_firebase_queue_worker');
  $chunks = array_chunk($entity->getRecipients(), $config['user_count'] ?? 100);

  $data = ['entity' => $entity];
  foreach ($chunks as $chunk) {
    $data['recipients'] = $chunk;
    $queue->createItem($data);
  }
}
